[package]
name = "cairo_template"
version = "0.1.0"
description = "A minimal template for developing with Cairo 1.0"
homepage = "https://github.com/auditless/cairo-template"

[scripts]
test = "protostar test"
# Add your own custom commands and run them with `scarb run <command>`

[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
