[package]
name = "cairo_template"
version = "0.1.0"
description = "A minimal template for developing with Cairo 1.0"
homepage = "https://github.com/auditless/cairo-template"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."
# Add your own custom commands and run them with scarb run <command>

# Uncomment if you want to use dependencies
# Note: currently testing doesn't work with dependencies
# [dependencies]
# quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }